FROM python:3.9-slim-buster

ARG DAGSTER_VERSION

ENV DOCKER_BUILDKIT=1
# Install system dependencies
RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    git \ 
    openssh-client \ 
    cmake \
    docker.io

# Install Python packages
RUN pip3 install --upgrade pip && \
    pip3 install \
    dagster==${DAGSTER_VERSION} \
    dagster-webserver==${DAGSTER_VERSION} \
    dagster-dbt \
    dagster-docker \
    dagster-slack \
    dagster-gcp \
    pyodbc \
    requests \
    xgboost \
    bigquery_schema_generator

# Enable experimental features for Docker-in-Docker
RUN echo '{"experimental": true}' | tee /etc/docker/daemon.json

ENV DAGSTER_HOME=/workspaces/dagster-nhl/dagster-code/sports-code
