FROM python:3.10-slim

# Checkout and install dagster libraries needed to run the gRPC server
# exposing your repository to dagit and dagster-daemon, and to load
# the DagsterInstance

RUN pip install \
    dagster \
    dagster-dbt \
    dagster-docker \
    dagster-slack \
    dagster-gcp 

RUN pip install \
    pyodbc \
    requests \
    xgboost
    
ENV DAGSTER_HOME=/opt/dagster/dagster_home