nhl_dbt:
  outputs:
    prod:
      type: postgres
      threads: 1
      host: "{{ env_var('DB_HOST') }}"
      port: 25060
      user: "{{ env_var('DB_USER') }}"
      pass: "{{ env_var('DB_PASSWORD') }}"
      dbname: nhl_stats

  target: prod