nhl_dbt:
  outputs:
    prod:
      type: postgres
      threads: 1
      host: "{{ env_var('DB_HOST') }}"
      port: "{{ env_var('DB_PORT') }}"
      user: "{{ env_var('DB_USER') }}"
      pass: "{{ env_var('DB_PASSWORD') }}"
      dbname: nhl_stats
      schema: public

  target: prod