version: 2
models:
  - name: game_data
    description: "Flattened game_data with all home and away data for each game"
    config:
      meta:
        partition_expr: game_date
        dagster:
          auto_materialize_policy:
            type: eager
          freshness_policy:
            maximum_lag_minutes: 30
  - name: nfl_features
    description: "NFL features to feed into a model"
    config:
      meta:
        dagster:
          auto_materialize_policy:
            type: eager
          freshness_policy:
            maximum_lag_minutes: 30