version: 2

sources:
  - name: nhl_ingestion
    database: corellian-engineering-co
    schema: NHLData
    tables:
      - name: schedule_raw
        meta:
            dagster:
              asset_key: ["schedule_raw"] # This metadata specifies the corresponding Dagster asset for this dbt source.
      - name: game_data_raw
        meta:
            dagster:
              asset_key: ["game_data_raw"] # This metadata specifies the corresponding Dagster asset for this dbt source.
