version: 2

sources:
  - name: nhl_ingestion
    database: nhl_stats
    schema: raw
    tables:
      - name: raw_game_data
        identifier: game_data
      - name: raw_schedule_data
        identifier: schedule_data
