version: 2

sources:
  - name: raw_data
    database: nhl_stats
    schema: raw
    tables:
      - name: game_data
        identifier: raw_game_data
      - name: schedule_data
        identifier: raw_schedule_data
