version: '3.9'
services:
  metabase:
    image: metabase/metabase:latest
    container_name: metabase
    hostname: metabase
    volumes:
      - /home/metabase:/metabase-data
    environment:
      MB_DB_TYPE: postgres
      MB_DB_DBNAME: metabaseappdb
      MB_DB_PORT: 5432
      MB_DB_USER: metabase
      MB_DB_PASS: mysecretpassword
      MB_DB_HOST: postgres
      MB_DB_FILE: /metabase-data/metabase.db
    networks:
      - metanet1
      - home_default
    healthcheck:
      test: curl --fail -I http://localhost:3000/api/health || exit 1
      interval: 15s
      timeout: 5s
      retries: 5
    labels:
      # traefikv2
      - "traefik.enable=true"
      - "traefik.http.routers.metabase.tls=true"
      - "traefik.http.routers.metabase.rule=Host(`metabase.corellianengineeringco.com`)"
      - "traefik.http.routers.metabase.tls.certresolver=le"
      - "traefik.http.routers.metabase.entrypoints=websecure"
      - "traefik.http.services.metabase.loadbalancer.server.port=3000"

  postgres:
    image: postgres:latest
    container_name: postgres
    hostname: postgres
    environment:
      POSTGRES_USER: metabase
      POSTGRES_DB: metabaseappdb
      POSTGRES_PASSWORD: mysecretpassword
    networks:
      - metanet1

networks:
  mealie:
    name: metanet1
    external: false
  home_default:
    name: home_default
    external: true