version: "3.7"

services:
  mlflow:
    image: ghcr.io/mlflow/mlflow:v2.11.3

    networks:
      - home_default

    command: mlflow server --host 0.0.0.0 --port 80 --serve-artifacts

    volumes:
      - /ssd-mlflow-01/mlruns:/mlruns/
      - /ssd-mlflow-01/mlartifacts:/mlartifacts/
    
    labels:
      # traefikv2
      - "traefik.enable=true"
      - "traefik.http.routers.mlflow.tls=true"
      - "traefik.http.routers.mlflow.rule=Host(`mlflow.corellianengineeringco.com`)"
      - "traefik.http.routers.mlflow.tls.certresolver=le"
      - "traefik.http.routers.mlflow.entrypoints=websecure"
      - "traefik.http.services.mlflow.loadbalancer.server.port=80"

networks:
  home_default:
    name: home_default
    external: true
